spring:
  application:
    name: api

server:
  port: 8203

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8201/eureka/

#mysql
#dataSource:
#  ctx:
#    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#    dataSource:
#      url: jdbc:mysql://localhost:3306/second_hand?useSSL=false
#      user: root
#      password: root
#      cachePrepStmts: true
#      prepStmtCacheSize: 250
#      prepStmtCacheSqlLimit: 2048
#    connectionTimeout: 30000
