spring:
  application:
    name: ribbon

server:
  port: 8202

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/
    fetch-registy: true
    instance:
      prefer-ip-address: true

