spring:
  application:
    name: api

server:
  port: 8201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/
    fetch-registry: true
    instance:
      prefer-ip-address: true

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

feign:
  hystrix:
    enabled: true



#mysql
#dataSource:
#  ctx:
#    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#    dataSource:
#      url: jdbc:mysql://localhost:3306/second_hand?useSSL=false
#      user: root
#      password: root
#      cachePrepStmts: true
#      prepStmtCacheSize: 250
#      prepStmtCacheSqlLimit: 2048
#    connectionTimeout: 30000
